### ISSUE TITLE
Differentiate the Cloud Credential for different compute from same cloud

### ISSUE THREAD

**Issue by mkumatag** [openshift/cloud-credential-operator#382]
**Overview:**

Right now I see CredentialsRequest's are mapped to individual Cloud providers like AWS, Azure, IBMCloud etc. In IBMCloud we have different offerings for the compute like VPC, PowerVS contains different policies, ACL but shares common IAM model and same CredentialsRequest code written can be used with different policies.

**Existing Solution:**

**Solution 1**: Include all the possible ACL in the single CredentialsRequest

```yaml
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-ibmcloud
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: IBMCloudProviderSpec
    policies:
      - <polices for vpc>
      - <polices for powervs>
```

Pros:
- One CR for the platform

Cons:
- in-cluster components will have wider ACLs

**Solution 2**: Create multiple CRs

for vpc:
```yaml
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-ibmcloud
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: IBMCloudProviderSpec
    policies:
      - <polices for vpc>
```

for powervs:

for vpc:
```yaml
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-ibmcloud
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: IBMCloudProviderSpec
    policies:
      - <policies for powervs>
```

Pros:
- Better ACL with different CRs

Cons:
- Still not foolproof, still in-cluster components can see this additional CR and can be used accidentally.

**Proposed solution:**

1. Include the label for the CR with the subresource mentioned 
e.g: 

```yaml
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    cloudcredential.openshift.io/compute-type: powervs
  name: openshift-machine-api-ibmcloud
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: IBMCloudProviderSpec
    policies:
      - <policies for powervs>
```
2. Use this label during the CR extract from the release image:
e.g: `$ oc adm release extract --credentials-requests --cloud=ibmcloud --selector cloudcredential.openshift.io/compute-type= powervs quay.io/<path_to>/ocp-release:<version>`
3. Run the ccoctl command with no changes

Pro:
- All the required in-cluster components will have only required credentials
- No need to change anything in the ccoctl
- No need to change existing CRs which does not need any such classifications

Cons:
- Need to include additional selector to the `oc adm release extract`
- Doc needs to be updated
- Any existing CRs need classifications need to be updated.

**Comment by joelddiaz** [comment]
I think this approach is reasonable. I would probably name it more generically than `compute-type`. Maybe `sub-platform` or something like that. So that if - for example - running OpenShift on AWS on GovCloud needs some special/different permissions, we can call it out as a "sub-platform" (that really has nothing to do with compute-type.
:+1:

**Comment by joelddiaz** [comment]
Actually, this could complicate things more than I initially thought. What does the Infrastructure CR look like on IBMCloud Power vs non-Power?

**Comment by mkumatag** [comment]
> Actually, this could complicate things more than I initially thought. What does the Infrastructure CR look like on IBMCloud Power vs non-Power?
> Basically, what I'm thinking about here is if we were to implement an in-cluster actuator (for which we presently have no plans for IBMCloud), how would that actuator know which CredentialsRequest object to process?

How about even that actuator will process CRs based on the selector(labels) if specified for the given platform..

**Comment by joelddiaz** [comment]
Now that I've learned that IBMCloud for power and x86 are effectively two different platforms https://github.com/openshift/api/blob/master/config/v1/types_infrastructure.go#L231 and https://github.com/openshift/api/blob/master/config/v1/types_infrastructure.go#L243 , and considering the the IAM policies can cover the permissions for both of these platforms...

Just brainstorming here: perhaps we can bury this detail in https://github.com/openshift/cloud-credential-operator/blob/master/pkg/apis/cloudcredential/v1/types_ibmcloud.go#L27 . Maybe some kind of sub-platform type field to say "this policy is for 'powervs vs ibmcloud' (following the naming of the platforms in the openshift/api's Infrastructure definition). We can also treat the field holding an empty string as meaning "applies to both platforms".

Then the ccoctl ibmcloud subcommands can respect a --sub-platform (we can debate the naming separately) where needed to filter between the appropriate IAM policies to mint.

FWIW, I prefer formalizing this idea of powervs vs ibmcloud in the API spec vs using labels/annotations.

@mkumatag @akhil-rane WDYT?

**Comment by akhil-rane** [comment]
if we have separated out IBMCloud and PowerVS as 2 different providers in Infrastructure CR, why not do the same in CCO and have 2 separate credentials requests?

for ibmcloud:

apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-ibmcloud
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: IBMCloudProviderSpec
    policies:
      - <polices for ibmcloud>

for powervs:

apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-ibmcloud
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: PowerVSProviderSpec
    policies:
      - <policies for powervs>

**Comment by joelddiaz** [comment]
@akhil-rane This is definitely another option where we could treat the CredReq providerSpec as different. But in reality the two "platforms" are identical (IAM-wise). The IAM policies in IBMCloud don't differentiate between powervs policies and non-powervs policies. It's just a different set of permissions that happen to be necessary for launching/setting up Power instances.
If one day there is a powervs version2, then presumably the permissions for powervs and non-powervs could be identical. With my proposal, if/when powervs and non-powervs merge (permissions-wise), we just stop filling out the "sub-platform" field and deprecate the "v1 powervs" CredReqs.

From @mkumatag 's example, it looks like there is nothing stopping us from putting in non-powervs specific policies in the PowerVSSpec.

It's all kind of weird having to think about the same cloud as different permissions-wise...

**Comment by mkumatag** [comment]
> Then the ccoctl ibmcloud subcommands can respect a --sub-platform (we can debate the naming separately) where needed to filter between the appropriate IAM policies to mint.
> 
> FWIW, I prefer formalizing this idea of powervs vs ibmcloud in the API spec vs using labels/annotations.
> 
> @mkumatag @akhil-rane WDYT?

The main reason I'm leaning towards labels is that I didn't want to limit this feature only of the sub-provider or very specific to a platform to reuse wherever necessary. e.g: can be used for the managed vs unmanaged, govcloud etc.. for any such configuration if we need a different set of CRs for the same platform this will become easy.

**Comment by joelddiaz** [comment]
We talked this over as a team, and with the realization that powervs is its own distinct platform, it makes sense to just have an IBMCloudProviderPowerSpec for the CredentialsRequest CRD. We can reuse the policy definitions of course, but that will be hidden behind an IBMCloudProviderPowerVSSpec that just happens to have the same policy definition.

I expect the AliCloud implementation will do something similar as my understanding is that the AliCloud policy format follows the AWS one.

This should make it clear what to extract when doing the `oc adm release extract` so that it follows existing documentation/behaviors.

**Comment by mkumatag** [comment]
> We talked this over as a team, and with the realization that powervs is its own distinct platform, it makes sense to just have an IBMCloudProviderPowerSpec for the CredentialsRequest CRD. We can reuse the policy definitions of course, but that will be hidden behind an IBMCloudProviderPowerVSSpec that just happens to have the same policy definition.
> 
> I expect the AliCloud implementation will do something similar as my understanding is that the AliCloud policy format follows the AWS one.
> 
> This should make it clear what to extract when doing the `oc adm release extract` so that it follows existing documentation/behaviors.

Alright! I will explore this and have some prototype ready for next review, flow looks like below:

CR:
```yaml
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-ibmcloud
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: IBMCloudProviderPowerVSSpec
    policies:
      - <policies for powervs>
```

oc adm command
```shell
$ oc adm release extract --credentials-requests --cloud=powervs quay.io/<path_to>/ocp-release:<version>
```

ccoctl command:

```shell
# ccoctl will have the logic to process both IBMCloudProviderSpec and IBMCloudProviderPowerVSSpec
$ ccoctl ibmcloud create-service-id --credentials-requests-dir <directory> --name <name>
```

one disadvantage I see with this approach is that we will end up having duplicate CRs with same policies for the both the platform even for the common components like ingress.
